### ISSUE TITLE
Two questions: protected_files and enclave key at runtime

### ISSUE THREAD

**Issue by quertenmont** [gramineproject/gsc#110]
Hello,

I am continuing my exploration of GSC+SGX generated enclave, and I am hurting a new issue and I have a more general question.

Let starts by the issue:
I have a mounted volume in my docker image (and container) that is located at "/resources",
Note that this volume is initially empty.

I'd like to mount this directory and access it from within my GSCfied running container.
If in my gsc manifest I specify 
sgx.allowed_files = [ "file:/resources/" ]
It all works fine.

On the other hand, if I use instead
sgx.trusted_files = [ "file:/resources/" ],
then I have a permission issues when trying to write in this directory.

I would have prefer to use the trusted_files paradigm to delegate the file on disk encryption to gramine and make my life easier.
Any idea of what could cause the permission denied error ?

I've also tried, without success, with:
fs.mounts = [
  { type = "encrypted", path = "/resources", uri = "/resources", key_name = "file_key" },
]

Now, the general question.
Can I retrieve somehow (from within the enclave) a private/public key pair that is only known by the enclave ?
I was hoping to find that in the /attestation/keys directory, but this one is initially empty and acquire a /attestation/key/default file after I generate an attestation for the enclave, but that default key is actually empty.

I suppose it's related to 
https://gramine.readthedocs.io/en/stable/attestation.html#high-level-secret-provisioning-interface,
but I am not sure.  Also when I setup an env variable SECRET_PROVISION_CONSTRUCTOR=1, nothing happens.

I was hoping to see something either in /attestation/keys/  or an env variable SECRET_PROVISION_SECRET_STRING to be created.  But none of this happened.

Thanks in advance for your advices,
Loic

**Comment by quertenmont** [comment]
Ok, I tried...

I am using a gsc fied container built with the following manifest:
```
loader.pal_internal_mem_size = "256M"
loader.insecure__use_host_env = true
libos.check_invalid_pointers = false
loader.env.KMP_AFFINITY = "granularity=fine,noverbose,compact,1,0"
sgx.remote_attestation = "dcap"
sgx.enclave_size = "1G"
sgx.preheat_enclave = true
sgx.thread_num = 8

#sgx.allowed_files = [ "file:/resources/" ]   ### REMARK, IF I USE THIS INSTEAD OF FS.MOUNTS IT WORKS

fs.mounts = [
  { type = "encrypted", path = "/resources", uri = "/resources", key_name = "_sgx_mrsigner" },
]
```

when I execute it, It fails with the following log+error:
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
Detected a huge manifest, preallocating 64MB of internal memory.
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

[P1:T1:] error: error mounting "/resources" (encrypted) under /resources: -22
[P1:T1:] error: Error during libos_init() in init_mount (-22)
```

Any Idea?
Anything special, I should do because I am using gsc instead of a bare gramine-sgx ?

**Comment by dimakuv** [comment]
I may have misunderstood what you want exactly. I was expecting that you will create the `/resources`-corresponding directory on the host, that will store the encrypted files, and you'll mount it like this:
```sh
docker run --volume=<your-empty-dir-on-host>:/resources:rw ...
```

> `[P1:T1:] error: error mounting "/resources" (encrypted) under /resources: -22`

This error happens because there is no `/resources` directory inside the (GSC-fied) Docker container that you're running. See my suggestion above how to make this directory visible to the Docker container.

**Comment by quertenmont** [comment]
Hi @dimakuv ,

I am running on kubernetes, so I can't simply run that command,
but for sure my volume is properly mounted on the host and is accessible.
How do I know?   because when I mount the volume with sgx.allowed_files = [ "file:/resources/" ], it works like a charm and my data are preserved on disk even if I remove and restart my kubernetes pod running the gsc container.

So the cause of the error must be somewhere else I fear....
but I have no idea where it could be.

Loic

**Comment by dimakuv** [comment]
> because when I mount the volume with sgx.allowed_files = [ "file:/resources/" ], it works like a charm and my data are preserved on disk

This is slightly different. `sgx.allowed_files` does **not** check on startup whether the directory `/resources` exists or not. And I assume that your application does an equivalent of `mkdir -p /resources` and then starts creating files in it.

On the other hand, `fs.mounts = [ {"encrypted"} ]` **checks** on startup whether the directory exists or not (actually, I'm not even sure why Gramine does it, or maybe it's a bug).

So this observation doesn't prove to us that Kubernetes deployment actually mounts any volume. If you didn't specify this `/resources` volume explicitly in the Kubernetes deployment file (I guess in some YAML config), then I would expect that your containers do **not** have this directory mounted at all.

**Comment by quertenmont** [comment]
Hi @dimakuv 

I do specify and mount the volume /resources in my kubernetes config.
It is NOT my application that creates it.  

As I said previously, my application store files in this directory, and I am sure that the volume connected through kubernetes/docker/gsc and whatever other actor in the chain is properly working, because I can see that my files are preserved when I wipeout everything and recreate everything using sgx.allowed_files.

Why fs.mounts reports and error is beyond my control (and understanding) but it's certainly not because the directory does not exists on the host.

Any suggestion to debug what is going on here ?

Loic

**Comment by mkow** [comment]
@quertenmont: Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine. If you need support then either:
- use GitHub Discussions,
- ask on our Gitter (https://gitter.im/gramineproject/community),
- or send an email to users@gramineproject.io.
