### ISSUE TITLE
GSC `master` should use Gramine `master` branch, not `v1.3.1`

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#115]
## Description
When gsc master is built for gramine v1.3.1 on dcap setup, it fails with error error: **Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded.**

This failure is caused by the changes in  gsc repo for [SGX driver ](0b60fa28aab0c9bc1b907230879235870f600b66) and with the the config yaml template which was modified to build with in-kernel driver

For another description of the same problem, see https://github.com/gramineproject/gsc/issues/114.

## Steps to reproduce
1. Copy config.yaml.template to config.yaml
2. Specify Gramine commit as v1.3.1 in config.yaml
3. Follow the steps from [README](https://github.com/gramineproject/gsc/blob/master/test/README.rst)

## Expected results
**Since, we are building on dcap setup, the sgx mountings are /dev/sgx/enclave and /dev/sgx/provision., so the device path is updated in docker run command**

**docker run --device=/dev/sgx/enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls**

```
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------
bin
boot
dev
etc
gramine
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
```

## Actual results
**docker run --device=/dev/sgx/enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls**
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded.
error: load_enclave() failed with error -2
```

**Comment by mkow** [comment]
These versions are not compatible. You should either use GSC v1.3.1 and Gramine v1.3.1, or both on master.

**Comment by mkow** [comment]
Ok, that is actually an issue in GSC. Could you change the title of this issue? I'll reopen it then.
Also, please submit a PR fixing this (if you have time).

**Comment by anjalirai-intel** [comment]
@mkow I will push a PR to fix this. Can you please open this issue

**Comment by dimakuv** [comment]
I'd like to note that this error can happen only on older deployments (like Azure AKS which uses Ubuntu 18.04 and Linux 5.4). Basically, this error can happen **only on Linux 5.10 and less**, which do not have an in-kernel SGX driver (which has the name `/dev/sgx_enclave`) and must use the "legacy" DCAP out-of-tree driver (which has the name `/dev/sgx/enclave`).

**Comment by mkow** [comment]
> [anjalirai-intel](https://github.com/anjalirai-intel) changed the title ~GSC Master is failing for Gramine v1.3.1 on dcap setup with load_enclave error~ GSC master is not compatible with Gramine v1.3.1

Eh, I'm not sure you understood the issue... It's not a bug that "GSC master is not compatible with Gramine v1.3.1", it's the intended behavior.
I fixed the title myself.
