### ISSUE TITLE
Failed to build unsigned graminized Docker image

### ISSUE THREAD

**Issue by Antone077** [gramineproject/gsc#125]
Hi,I want to run /gsc/test this [examples](https://github.com/gramineproject/gsc/tree/master/test) ,but when I run ./gsc build command.It reports errors as this:
`Step 6/30 : RUN git clone https://github.com/gramineproject/gramine.git /gramine

 ---> Running in c0d7cf1bead6
Cloning into '/gramine'...

fatal: unable to access 'https://github.com/gramineproject/gramine.git/': Could not resolve host: github.com

Failed to build unsigned graminized Docker image `gsc-ubuntu18.04-bash-unsigned`.`

My steps:

`cd gsc-1.3.1
sudo apt-get install docker.io python3 python3-pip
pip3 install docker jinja2 tomli tomli-w pyyaml
pip3 install toml  # for compatibility with Gramine v1.3 or lower
cp config.yaml.template config.yaml

docker build --tag ubuntu18.04-bash --file test/ubuntu18.04-bash.dockerfile .
sudo ./gsc build --insecure-args ubuntu18.04-bash test/ubuntu18.04-bash.manifest
`
These are the last outputs from the terminal:
`Step 4/30 : RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main'     > /etc/apt/sources.list.d/intel-sgx.list     && apt-key add intel-sgx-deb.key

 ---> Using cache
 ---> f6b6034db113
Step 5/30 : RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y libsgx-dcap-quote-verify-dev

 ---> Using cache
 ---> 59662e39e4c1
`

Do you have an idea how to get more detailed information to figure out what's going wrong?

**Comment by mkow** [comment]
`Could not resolve host: github.com` means that something's probably wrong with your network inside the container, not Gramine / GSC.
Also, please use Markdown when formatting your issues, what you sent is unreadable.
