### ISSUE TITLE
GSC doesn't support `debugoptimized` buildtype

### ISSUE THREAD

**Issue by jkr0103** [gramineproject/gsc#129]
`debugoptimized` build is close to `release` build in terms of performance. So to record the perf data for a application runnings in GSC, `debugoptimized` buildtype is the best option but GSC doesn't provide any option to build `debugoptimized` buildtype.

## Expected results
GSC should have `debugoptimized` buildtype option.
## Actual results
GSC doesn't support `debugoptimized` buildtype.

**Comment by dimakuv** [comment]
That's true. This shouldn't be hard to implement.

But on the other hand, I'm a bit reluctant to add more flags to GSC. Isn't this `debugoptimized` feature used purely for testing, and purely by Gramine/GSC developers?

I am currently against adding this feature in user-facing GSC, but instead I think developers can simply replace this line of code: https://github.com/gramineproject/gsc/blob/0b60fa28aab0c9bc1b907230879235870f600b66/templates/Dockerfile.common.compile.template#L31

with this:
```
 --buildtype={% if debug %}debugoptimized{% else %}release{% endif %} \ 
```

**Comment by jkr0103** [comment]
This was asked by internal customer and they are already trying the same `--buildtype={% if debug %}debugoptimized{% else %}release{% endif %} \ `.

But there could be scenarios where we ask customers to get `perf data` for some issues they see with GSC image, so this functionality should be built-in, I feel.
