### ISSUE TITLE
Exception: Duplicate key with different values found: `loader.log_level`

### ISSUE THREAD

**Issue by Dadoias** [gramineproject/gsc#134]
Hello there

## Description of the problem
I modified the Manifestfile, exactly I want to change the log_level, but after run `$ ./gsc build --insecure-args ${image} ManifestFile.manifest`,  it gives me this error:
```
Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "/home/trustup/gsc/./gsc.py", line 513, in main
    return args.command(args)
  File "/home/trustup/gsc/./gsc.py", line 246, in gsc_build
    merged_manifest_dict = merge_two_dicts(user_manifest_dict, entrypoint_manifest_dict)
  File "/home/trustup/gsc/./gsc.py", line 144, in merge_two_dicts
    merge_two_dicts(dict1[key], dict2[key], path + [str(key)])
  File "/home/trustup/gsc/./gsc.py", line 150, in merge_two_dicts
    raise Exception(f'''Duplicate key with different values found: `{".".join(path +
Exception: Duplicate key with different values found: `loader.log_level`
```

This is the manifest: 
```
sgx.enclave_size = "2G"
sgx.max_threads = 18
sys.insecure__allow_eventfd = true

loader.log_level = "trace"
```

Any suggestions?

**Comment by dimakuv** [comment]
Yes, this is not allowed in GSC. You can achieve the same with adding the `--debug` flag during `gsc build` step.

But having `loader.log_level` in the manifest for GSC is not possible. I'm not sure if we want to allow such behavior...

If you want to run with `trace` log level, then you should change this line: https://github.com/gramineproject/gsc/blob/a0bb1f54093ed7d0fdcef5f27f66c428ced73dce/templates/entrypoint.common.manifest.template#L7

This means that you need to modify the internals of GSC...

**Comment by Dadoias** [comment]
Ok thanks, I changed the line like that and it worked!
```
loader.log_level = {% if debug %} "all" {% else %} "trace" {% endif %}
```
