### ISSUE TITLE
LD_LIBRARY_PATH is missing for debian template

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#135]
## Description of the problem
LD_LIBRARY_PATH is missing for debian template in gsc

## Steps to reproduce
While curation mysql with Debian 11, it keeps on printing **"Emulating a raw syscall instruction. This degrades performance, consider patching your application to use Gramine syscall API."** to the console, and the server did not start. 

## Solution
https://github.com/gramineproject/gsc/blob/master/templates/ubuntu/entrypoint.manifest.template#L7 should also be added in https://github.com/gramineproject/gsc/blob/master/templates/debian/entrypoint.manifest.template

**Comment by dimakuv** [comment]
Yes, agreed, this is clearly a bug.

**Comment by aneessahib** [comment]
@jkr0103 is working on moving the LD_LIBRARY_PATH to the Debian template.
