### ISSUE TITLE
Old GPG Key

### ISSUE THREAD

**Issue by Villain88** [gramineproject/gsc#151]
Error installing libsgx-dcap-quote-verify-dev
## Expected results
Download fresh gpg key via wget or curl from  https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
## Actual results
Use hardcoded key

**Comment by dimakuv** [comment]
I submitted three PRs covering all uses of the Intel SGX PGP key in Gramine repos:
- https://github.com/gramineproject/gsc/pull/152
- https://github.com/gramineproject/contrib/pull/45
- https://github.com/gramineproject/gramine/pull/1369

We'll review them asap and merge. @woju @mkow @kailun-qin Could you please prioritize these PRs?

**Comment by dimakuv** [comment]
This was fixed completely now, closing.
