### ISSUE TITLE
License for gsc?

### ISSUE THREAD

**Issue by nmwael** [gramineproject/gsc#154]
Hi it's unclear to me what kind of license GSC are under? Is it just inheriting the Gramine license or?

**Comment by dimakuv** [comment]
The GSC license should be the same as the Gramine license, i.e. LGPL 3.0.

But I see that we don't have a LICENSE file in the repo. We should add it...

**Comment by nmwael** [comment]
Isn't lgpl too restrictive for this kind of template project? For example if one had to add something to the templates or the python script itself? Couldn't it violate the terns?

**Comment by dimakuv** [comment]
@nmwael We discussed this during the Gramine meeting, and I created an issue to work on this: #161.

**Comment by dimakuv** [comment]
> Isn't lgpl too restrictive for this kind of template project? For example if one had to add something to the templates or the python script itself? Couldn't it violate the terns?

This is a good point. Yes, we're currently thinking of moving to the BSD license.

**Comment by nmwael** [comment]
Thanks again :)
