### ISSUE TITLE
OCI compliant gsc

### ISSUE THREAD

**Issue by rashane-murray** [gramineproject/gsc#16]
Hey there, just a wondering dev interested in unikernels but I was reading on your project's efforts to make unikernel containers and was wondering why not make an OCI-compliant base image from graphene(gramine?) that way it can take advantage of the existing ecosystem of available tools. Alternatively, if graphene dynamically adds only the necessary OS libraries required by a specific application to run, why not make a build system plugin for existing CI/CD pipelines that wraps the deployed app in a OCI-compliant, graphene unikernel that would then get run? 

This is all just a suggestion, I don't have the proper expertise on LibOSs nor do I know your internal priorities (it seems SGX is high on that list) to know why you're making the design decisions you are.

**Comment by dimakuv** [comment]
> why not make a build system plugin for existing CI/CD pipelines that wraps the deployed app in a OCI-compliant, graphene unikernel that would then get run

This is a good suggestion and definitely something that we will add at some point to Graphene. There is no specific reason why we're using an ad-hoc Python-based tool (our "GSC" tool) instead of writing a plugin for some existing CI/CD framework. The only reason is: that was simpler and faster.

As you correctly mentioned, our top priority currently is making Graphene with Intel SGX to be production quality. This GSC tool is a quick way to add Graphene-SGX abilities to existing Docker images.

**Comment by rashane-murray** [comment]
I understand but how about a graphene base image? Also, after further reading I notice graphene's roots are in Microsoft research's drawbridge project, is there (or more appropriately, will there be be) support for Windows guests?

**Comment by mkow** [comment]
Currently we don't have any client / party interested in Windows PAL, but if there appears one, then why not ;) Also, I heard that a @chiache's student once tried to implement it as part of some university research.

**Comment by dimakuv** [comment]
> ...is there (or more appropriately, will there be be) support for Windows guests?

There is currently no support for Windows backend. Note that "Windows guests" is not something that Graphene/Gramine aims to do: the guest app inside Gramine always executes as if it runs in the Linux environment.

So in Graphene/Gramine, it is like this:
- The guest ("the inside of Gramine") is an app built for Linux.
- The backend ("the outside of Gramine", aka "the host") is currently one of the: normal Linux, SGX enclave on Linux. Maybe in the future we'll add the Windows backend.

**Comment by dimakuv** [comment]
> I understand but how about a graphene base image?

We have a way to build the Graphene/Gramine base image. But we currently don't host any pre-built Gramine image anywhere on the internet.

**Comment by rashane-murray** [comment]
> > I understand but how about a graphene base image?
> 
> We have a way to build the Graphene/Gramine base image. But we currently don't host any pre-built Gramine image anywhere on the internet.

Oh well it would be be great if you did, that would make leveraging it even more appealing in the container space as images are bloated and insecure whereas a more minimal unikernel-based image could(would) solve that major issue so please consider releasing it!

**Comment by rashane-murray** [comment]
Thanks for your replies
