### ISSUE TITLE
GSC `build-gramine` creates different image than specified by user

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#181]
## Description of the problem
When we build the gramine image alone with gsc by giving an image name`bash20.04`, gsc automatically append `gsc` to the image name`gsc-bash20.04` during build-gramine and when this newly created image `gsc-bash20.04` updated to config yaml, build fails.

Ideally it should create the image with same name specified by user, but if gsc changes the name then same name should be used in config.yaml. It creates the confusion for what image name should be used in config.yaml. In order to make it work, currently image name should be specified without gsc in config

## Steps to reproduce
At this step, user has specified image name as `bash20.04`, but gsc creates image with `gsc-bash20.04`
```
$ ./gsc build-gramine bash20.04
Building base-Gramine Docker image `gsc-bash20.04`...
Step 1/9 : FROM ubuntu:20.04 AS gramine

 ---> 6df894023726
Step 2/9 : RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y         autoconf         bison         build-essential         coreutils         curl         gawk         git         libprotobuf-c-dev         linux-headers-generic         nasm         ninja-build         pkg-config         protobuf-c-compiler         protobuf-compiler         python3         python3-cryptography         python3-protobuf         wget            python3-pip            && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'

 ---> Running in b4732771773d
.....
.....
.....
Running custom install script '/bin/sh -c ln -sf ../../../libsecret_prov_verify_dcap.so "$MESON_INSTALL_DESTDIR_PREFIX"/lib/x86_64-linux-gnu/gramine/runtime/glibc/'
 ---> e229fa356e33
Successfully built e229fa356e33
Successfully tagged gsc-bash20.04:latest
Successfully built a base-Gramine Docker image `gsc-bash20.04`.
```

Updating the image in config yaml from previous step logs `Successfully built a base-Gramine Docker image gsc-bash20.04` the gsc build again tries to append `gsc` in front.

```
$ cat config.yaml | grep Image
        Image: "gsc-bash20.04"

$ ./gsc build --insecure-args ubuntu20.04-bash test/ubuntu20.04-bash.manifest
Cannot find base-Gramine Docker image `gsc-gsc-bash20.04`.
```
## Expected results
./gsc build-gramine should create image with same name specified by user and same should be updated in config yaml

**Comment by jkr0103** [comment]
I agree with @anjalirai-intel. Description of the image name argument [here](https://github.com/gramineproject/gsc/blob/43a9b9c7f919809178f9a77c76afae5165a1ce6d/gsc.py#L596) also says this should be the output image but after `build-gramine` if we check `docker images` then we don't find image with exactly the same name which now add confusion to what image name should be specified `config.yaml`.

**Comment by dimakuv** [comment]
Yes, I agree, this convention is whimsical.

I would suggest to modify as follows:
1. First try to find an image with the name specified in the command-line arguments / config file,
2. If failed, try to find an image with the name **prefixed with `gsc-`**,
3. If both attempts fail, then error out.

The item 2 is what currently happens. My suggestion is to add item 1. Item 2 then becomes a fallback (legacy) behavior.

**Comment by jkr0103** [comment]
Why do we want to support 2nd point? It might fail for the existing users if they use latest GSC release but error message would clear it that they have to re-build the gramine base image once, which is ok I feel.

or do we want to support it only for this release and remove later?

**Comment by dimakuv** [comment]
> Why do we want to support 2nd point? It might fail for the existing users if they use latest GSC release but error message would clear it that they have to re-build the gramine base image once, which is ok I feel.

But many people use GSC in automated scripts, so their scripts will suddenly fail all at once. I think we should give some grace degradation period for people to adjust their flows.

> or do we want to support it only for this release and remove later?

Yes, exactly.
