### ISSUE TITLE
Gramine Shielded Container + Named Pipe

### ISSUE THREAD

**Issue by YanAlmeida** [gramineproject/gsc#184]
## Description of the problem
I am using GSC to run a python application in a docker container inside a SGX Enclave. This container should be able to write to a named pipe and read from another, so it can communicate with another proccess.

After building and signing the image, I run:

sudo docker run --device=/dev/sgx_enclave -v /tmp/named_pipes:/tmp/named_pipes gsc-yanalmeida91/sgx-blockchain-pull:latest

If there are no named pipes in /tmp/named_pipes, the application tries to create them. It does not throw any errors, but the command "open(WRITE_NAMED_PIPE_PATH, 'w')" throws an error of invalid arg.

If I create the named pipes beforehand, the command "os.path.exists()" returns False, but when the enclave tries to create it, receives Permission Denied error. If I remove the creation part of the code, I get the same Permission Denied error when trying to open the named pipes (both in read and write mode).

What is happening?

UPDATE: I found out that it's working for regular files. The problem is accessing the named pipes. Why? Is something missing in the manifest?

My manifest file:

loader.env.READ_PIPE_PATH = "/tmp/named_pipes/write_pipe"
loader.env.WRITE_PIPE_PATH = "/tmp/named_pipes/read_pipe"

sgx.allowed_files = ["file:/tmp/named_pipes/write_pipe", "file:/tmp/named_pipes/read_pipe"]

sgx.enclave_size = "4G"
sgx.thread_num = 8

## Steps to reproduce

You can try to reproduce it by graminizing my base docker image: yanalmeida91/sgx-blockchain-pull:latest and trying to run it.
I'm graminizing it in virtual machines in azure, running a bootstraping script:

    #!/bin/bash
    sudo apt-get update
    sudo apt-get install -y build-essential ocaml automake autoconf libtool wget python3 python3-pip libssl-dev dkms
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    sudo wget https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/${var.sgx_driver_distro_name}/${var.sgx_driver_file_name}
    sudo chmod 777 ${var.sgx_driver_file_name}
    sudo ./${var.sgx_driver_file_name}
    sudo apt-get install -y docker.io

    sudo apt-get install git
    sudo pip3 install docker jinja2 tomli tomli-w pyyaml

    sudo docker pull ${var.dockerhub_image_sgx}
    sudo docker pull ${var.dockerhub_image_sgx_untrusted}

    git clone https://github.com/YanAlmeida/gsc-v1.5-adjustment.git
    sudo chmod -R 777 /gsc-v1.5-adjustment
    cd gsc-v1.5-adjustment

    cp config.yaml.template config.yaml
    echo "${file("./tee_machine_config/enclave-key.pem")}" > enclave-key.pem

    echo "${file("./manifest.txt")}" >> config.manifest

    sudo ./gsc build --insecure-args ${var.dockerhub_image_sgx} test/generic.manifest
    sudo ./gsc sign-image ${var.dockerhub_image_sgx} enclave-key.pem

    sudo rm enclave-key.pem

    sudo docker run -d --device=/dev/sgx_enclave  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket -v /tmp/named_pipes:/tmp/named_pipes gsc-${var.dockerhub_image_sgx}

## Expected results
Named pipes created and working with the enclave

## Actual results
Errors or named pipes created but not appearing on host folder via docker volume

**Comment by dimakuv** [comment]
Named pipes between a Gramine process and a non-Gramine process are **impossible**. This is due to security reasons. For more info, see the other of your issues: https://github.com/gramineproject/gramine/discussions/1669
