### ISSUE TITLE
GSC build for UBI9 and UBI9-minimal workloads are failing

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#220]
## Description of the problem
GSC build for UBI9 and UBI9-minimal workloads are failing

## Steps to reproduce

ubi9-bash.dockerfile:
```
FROM redhat/ubi9:9.4
RUN yum update -y
CMD ["bash"]
```

docker build --tag bash-test -f test/ubi9-bash.dockerfile .
./gsc build --insecure-args bash-test test/ubuntu20.04-bash.manifest

## Expected results
GSC build should be successful and able to run workload

## Actual results
GSC Build is failed to create unsigned image with error `Error: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried`

Logs: 
[gsc_rhel9_issue.log](https://github.com/user-attachments/files/17552964/gsc_rhel9_issue.log)

**Comment by sahason** [comment]
Please re-register the system again to get the updated `url` for `rhel-9-for-x86_64-resilientstorage-source-rpms`

**Comment by anjalirai-intel** [comment]
@sahason Done, it is working now
