### ISSUE TITLE
Update GSC with Gramine's new SGX Driver Requirements

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gsc#227]
## Description of the problem
As part of the [Remove support for OOT (out-of-tree) SGX driver commit](https://github.com/gramineproject/gramine/pull/2061) in the Gramine master branch, the options -Dsgx_driver, -Dsgx_driver_include_path, and -Dsgx_driver_device have been removed. Similar changes should be backported into GSC as well. Currently, workloads are failing during the Meson build with the error Unknown options: "sgx_driver, sgx_driver_include_path".`

**Comments from Gramine PR**
```
Since Gramine v1.9, we only support upstream, in-kernel driver and the
``-Dsgx_driver`` option, as well as associated ``-Dsgx_driver_include_path`` and
``-Dsgx_driver_device`` options, are gone.
```

## Steps to reproduce

https://github.com/gramineproject/gsc/tree/master/test#building-sample-images

## Expected results
GSC master should be fully compatible with Gramine master and kept up-to-date. Any significant changes made in Gramine that impact GSC should be updated to support Gramine and the new build requirements.

## Actual results
```
Step 9/9 : RUN cd /gramine     && meson setup build/ --prefix="/gramine/meson_build_output"        --buildtype=release        -Ddirect=enabled -Dsgx=enabled                        -Dsgx_driver=upstream -Dsgx_driver_include_path=/gramine/driver             && ninja -C build     && ninja -C build install

 ---> Running in 4517253c192f
The Meson build system
Version: 1.6.0
Source dir: /gramine
Build dir: /gramine/build
Build type: native build

meson.build:5:0: ERROR: Unknown options: "sgx_driver, sgx_driver_include_path"

A full log can be found at /gramine/build/meson-logs/meson-log.txt
Failed to build a base-Gramine Docker image `bash20.04`.
```

**Comment by adarshan-intel** [comment]
Please see #228
