### ISSUE TITLE
[finalize_manifest.py] Finalize manifest - traverse symlink directories

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gsc#25]
Converting the official mongo docker image to gsc fails because of the symlink /lib -> usr/lib, the finalize_manifest.py doesn't include the /lib directory in the manifest, due to os.walk not traversing symlinks, but later on the application tries to access the /lib directory.

**Comment by dimakuv** [comment]
Just a note: we encountered a similar issue in https://github.com/gramineproject/gsc/issues/36. I will close that issue since we already track the bug/missing functionality of GSC here.
