### ISSUE TITLE
Run Bash example in Azure - Missing SGX Driver

### ISSUE THREAD

**Issue by dzygann** [gramineproject/gsc#29]
Hi,

I try to run the GSC Bash example on an Azure machine. I followed the instructions in the [README](https://github.com/gramineproject/gsc/blob/master/test/README.rst).
I could build the container, but the last command `docker run ...` command runs into an error.

My first try was to run the command from the README file
```
$ sudo docker run --device=/dev/sgx_enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls
docker: Error response from daemon: error gathering device information while adding custom device "/dev/sgx_enclave": no such file or directory.
```

On my Azure machine is no `/dev/sgx_enclave` directory. Should it be there?
There is an `/dev/sgx` directory, which contains two character devices (`enclave` and `provision`).
If I pass this directory `--device` argument I get the same message as above at the end, but with some more steps before:
```
docker run --device=/dev/sgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls
++ find /gramine/meson_build_output/lib -type d -path '*/site-packages'
+ export PYTHONPATH=:/gramine/meson_build_output/lib/python3.6/site-packages
+ PYTHONPATH=:/gramine/meson_build_output/lib/python3.6/site-packages
++ find /gramine/meson_build_output/lib -type d -path '*/pkgconfig'
+ export PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
+ PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
+ '[' -z '' ']'
+ gramine-sgx-get-token --sig /entrypoint.sig --output /entrypoint.token
Attributes:
   ...
    date:        2021-11-02
+ gramine-sgx /entrypoint -c ls
error: Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded.
error: load_enclave() failed with error -2
```
I can run the bash example in the CI-Examples folder without any issues.
I saw in the README the line `change --device=/dev/sgx_enclave to your version of the Intel SGX driver if needed`. 
How I can figure this out?

**Comment by dimakuv** [comment]
1. Try `docker run --device=/dev/sgx/enclave`.

2. What is your `config.yaml`? I assume that you're using the default parameters for the `SGXDriver`. Unfortunately, the Azure machine seems to use the older DCAP driver, so you need to use the DCAP parameters in your `config.yaml`: https://github.com/gramineproject/gsc/blob/master/config.yaml.template#L17. After you change your `config.yaml` to the DCAP driver, rebuild your example completely.

**Comment by dzygann** [comment]
Hi @dimakuv 

> Try docker run `--device=/dev/sgx/enclave`.

Unfortunately, run into the same error message:

```
error: Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded.
error: load_enclave() failed with error -2
```
> After you change your `config.yaml` to the DCAP driver, rebuild your example completely.

I tried to use the following driver:
```
Repository: "https://github.com/intel/SGXDataCenterAttestationPrimitives.git"
Branch:     "DCAP_1.11 && cp -r driver/linux/* ."
```
I don't see an error message anymore, but a `killed` response

```
$ docker run --device=/dev/sgx/enclave  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls

++ find /gramine/meson_build_output/lib -type d -path '*/site-packages'
+ export PYTHONPATH=:/gramine/meson_build_output/lib/python3.6/site-packages
+ PYTHONPATH=:/gramine/meson_build_output/lib/python3.6/site-packages
++ find /gramine/meson_build_output/lib -type d -path '*/pkgconfig'
+ export PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
+ PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
+ '[' -z '' ']'
+ gramine-sgx-get-token --sig /entrypoint.sig --output /entrypoint.token
Attributes:
   ...
    date:        2021-11-03
+ gramine-sgx /entrypoint -c ls
/apploader.sh: line 18:    11 Killed                  gramine-sgx /entrypoint "${@}"
```
This seems to be a step forward, but what do I have to do next?

**Comment by dimakuv** [comment]
Try rebuilding and add `-d` to `gsc build` command. Like this:
```
./gsc build -d --insecure-args ubuntu18.04-bash test/ubuntu18.04-bash.manifest
```

This will build Gramine app with manifest that contains `loader.log_level = "all"`. This will give you some idea what's going on with `gramine-sgx` run.

**Comment by dzygann** [comment]
Hi @dimakuv 

> Try rebuilding and add `-d` to `gsc build` command. Like this:

Nice, I didn't know that one. Unfortunately, the output isn't more clear (at least not for me):

```
    date:        2021-11-03
+ gramine-sgx /entrypoint -c ls
debug: Token file: /entrypoint.token
debug: Read dummy DCAP token
debug: enclave created:
debug:     base:           0x0000000000000000
debug:     size:           0x0000000100000000
debug:     misc_select:    0x00000000
debug:     attr.flags:     0x0000000000000005
debug:     attr.xfrm:      0x0000000000000007
debug:     ssa_frame_size: 4
debug:     isv_prod_id:    0x00000000
debug:     isv_svn:        0x00000000
debug: adding pages to enclave: 0xffcf9000-0x100000000 [REG:R--] (manifest) measured
debug: adding pages to enclave: 0xffcd9000-0xffcf9000 [REG:RW-] (ssa) measured
debug: adding pages to enclave: 0xffcd5000-0xffcd9000 [TCS:---] (tcs) measured
debug: adding pages to enclave: 0xffcd1000-0xffcd5000 [REG:RW-] (tls) measured
debug: adding pages to enclave: 0xffc91000-0xffcd1000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xffc51000-0xffc91000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xffc11000-0xffc51000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xffbd1000-0xffc11000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xffbc1000-0xffbd1000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffbb1000-0xffbc1000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffba1000-0xffbb1000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffb91000-0xffba1000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xfb55d000-0xfb5ba000 [REG:R-X] (code) measured
debug: adding pages to enclave: 0xfb7b9000-0xfb7bd000 [REG:RW-] (data) measured
debug: adding pages to enclave: 0xfb7bd000-0xffb91000 [REG:RW-] (bss) measured
debug: adding pages to enclave: 0x10000-0xfb55d000 [REG:RWX] (free)
/apploader.sh: line 18:    11 Killed                  gramine-sgx /entrypoint "${@}"
```

Do you see something suspicious?

**Comment by dimakuv** [comment]
I don't see anything suspicious...

Could you check `dmesg` output of your Azure system? Maybe the Linux kernel / the SGX driver complain about something. It looks like Gramine is killed by the host Linux after the enclave is created (after ECREATE and EADD) and during enclave initialization (EINIT).

**Comment by dimakuv** [comment]
By the way, you're using this file: https://github.com/gramineproject/gsc/blob/master/test/ubuntu18.04-bash.manifest.

It has the enclave size of 4GB. Maybe this is too much for this Azure system? Try decreasing this size to 2GB, 1GB, etc.

I actually have a suspicion now. You're probably running an Azure VM instance. Depending on what kind of VM you chose, Azure VMs range from very small to very big. If you chose a small Azure VM instance, it will have something like 2-4GB of RAM -- this is not enough to start your Bash SGX enclave.

So:
- either buy a more powerful Azure VM with more RAM,
- or decrease the Bash enclave size

**Comment by dzygann** [comment]
Hi @dimakuv 

I have decreased the enclave size. It works! 
My machine has only 4GB.  So this was the issue.

Thank you very much! 

Question out of curiosity: Would it be possible to give the user a warning?

**Comment by dimakuv** [comment]
Well, yes, technically Gramine-SGX could check the total amount of RAM + swap space on startup, and print some warning in case this amount is dangereously small. What do others think? @mkow @boryspoplawski @pwmarcz We periodically have these questions from different people, and this is a quite obscure detail about Intel SGX -- should we add such a warning?

**Comment by mkow** [comment]
Such a check sounds very hacky and brittle.

> this is a quite obscure detail about Intel SGX

I don't think it's related to SGX? It's rather Bash+Linux saying "Killed" instead of "Killed (out of memory)", for complicated reasons. I guess this is something which all Linux users have to learn while waiting for The Year of Linux on Desktop.

**Comment by dimakuv** [comment]
> I don't think it's related to SGX?

But it is a quirk of SGX: even if the native application uses only 1MB of virtual memory, if the manifest has `sgx.enclave_size = 4GB`, the *enclavized application* will use *all 4GB* of virtual memory. This is very counter-intuitive for normal users.

The fact that Bash prints a useless "Killed" message is another story. Even if Bash would print "Killed because out of memory", users would still be extremely confused -- the native app runs fine but not the SGX one?!

**Comment by dimakuv** [comment]
The current consensus to improve user experience is to explain this caveat in `sgx.enclave_size` manifest option description: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#enclave-size

Other options considered:
- Better name than `sgx.enclave_size` (but decided it's already descriptive)
- Do nothing (this doesn't seem reasonable as we frequently receive such issues from users)
