### ISSUE TITLE
Support for non-root user with GSC docker container

### ISSUE THREAD

**Issue by sivashax** [gramineproject/gsc#30]
Support for non-root user with GSC docker build is needed. Currently support is available only for ROOT user.

## Steps to reproduce
1. copy the attached docker file into <Gramine Directory>/gsc/test folder.
2. Below command to build the docker.
	a. cd <Gramine Directory>/gsc
	b. docker build --tag ubuntu18.04-bash-nonroot --file test/ubuntu18.04-bash_nonroot.dockerfile .
	c. ./gsc build --insecure-args ubuntu18.04-bash-nonroot test/ubuntu18.04-bash.manifest
	d. ./gsc sign-image ubuntu18.04-bash-nonroot enclave-key.pem

## Expected results
Build is successful.

## Actual results
Below is the error seen with GSC build.
```
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
Failed to build unsigned graminized docker image `gsc-ubuntu18.04-bash-nonroot-unsigned`.
```

**Comment by sivashax** [comment]
[ubuntu18.04-bash-nonroot.txt](https://github.com/gramineproject/gsc/files/7504810/ubuntu18.04-bash-nonroot.txt)
Attached docker file

**Comment by aneessahib** [comment]
assign to me
