### ISSUE TITLE
Support for running application as non-root user inside GSC docker conatiner

### ISSUE THREAD

**Issue by sivashax** [gramineproject/gsc#31]
## Description of the problem
Support for running the application as non-root user inside GSC docker container is needed.

## Steps to reproduce
1. Create GSC docker with non-root user
2. Run the application inside docker container as non-root user. Ex, sudo -u <non-root user> <app>

## Expected results
Should be able to run the application as non-root user inside docker container

## Actual results
Running application with non-root user fails with below error.
+ xargs **sudo -u ovsa /ovms/bin/./ovms** --grpc_bind_address 127.0.0.1^M
+ MODEL_SERVER_PID=130^M
+ echo 'Model Server PID: 130'^M
Model Server PID: 130^M
+ echo 'Starting Nginx...'^M
Starting Nginx...^M
**sudo: PERM_INITIAL: getresuid: Function not implemented^M
sudo: unable to initialize policy plugin^M**
+ MODEL_SERVER_EXIT_CODE=123^M
+ echo 'Model server job finished with an exit code: 123'^M
Model server job finished with an exit code: 123^M
+ sudo -u ovsa nginx -g 'daemon off;'^M
+ NGINX_PID=102^M
+ echo 'Nginx PID: 102'^M
Nginx PID: 102^M
+ echo 102^M
+ wait 102^M
**sudo: PERM_INITIAL: getresuid: Function not implemented^M
sudo: unable to initialize policy plugin^M**
+ NGINX_EXIT_CODE=1^M
+ echo 'Nginx job finished with an exit code: 1'^M
Nginx job finished with an exit code: 1^M

**Comment by dimakuv** [comment]
#60 was merged, which should have solved this issue. Closing.
