### ISSUE TITLE
GSC Failed to build unsigned graminzed docker images

### ISSUE THREAD

**Issue by dzygann** [gramineproject/gsc#34]
Hi,

I try to run hashgraph in a GSC container. I could run it in successfully in gramine-sgx. Now I would like to run it also in a GSC.

This is my dockerfile: 

```
FROM ubuntu:20.04 AS build-stage
  
# suppress region selection during dependency installation
ARG DEBIAN_FRONTEND=noninteractive

# install dependencies and build tools
RUN apt-get update && apt-get install --no-install-recommends -qq -y \
    cmake \
    automake \
    bison \
    flex \
    g++ \
    git \
    libboost-all-dev \
    libevent-dev \
    libssl-dev \
    libtool \
    make \
    pkg-config \
    openssl \
    apt-utils

# copy the source code into the container
COPY examples/hashgraph /hashgraph

# switch to build folder
WORKDIR /hashgraph/build

# build
RUN cmake .. && make


# everything within the export-stage will be exported to the host
FROM scratch AS export-stage

# copy executable from build-state to export-stage
COPY --from=build-stage /hashgraph/build/hashgraph /build/hashgraph

# copy crypto material from build-state to export-stage
COPY --from=build-stage /hashgraph/tests/config /tests/config

# to avoid entrypoint issue
CMD ["bash"]
```

The docker build finish successfully. As soon as I run the `gsc build` it runs into a issue without details. I run the following command: 

```
./gsc build -d --insecure-args hashgraph test/hashgraph.manifest 
```   

These are the last outputs from the terminal:

```
 ---> 81fe0d2c8ac6
Step 8/22 : RUN apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y         binutils         libprotobuf-c-dev         locales         locales-all         openssl         python3         python3-pip         python3-protobuf     && python3 -B -m pip install click jinja2 protobuf 'toml>=0.10'

 ---> Running in 907471e22004
Failed to build unsigned graminized docker image `gsc-hashgraph-unsigned`.
```
Here is also my manifest content. I took it from the old PyTorch example: 

```
sgx.enclave_size = "16G"
sgx.thread_num = 32
sys.stack.size = "2M"

# Python's memory allocator by default creates a new arena for each thread, and each new arena
# allocates 128MB of memory. By default, PyTorch creates as many threads as there are available CPU
# cores, so this may quickly deplete available enclave memory (e.g. Python eats 2GB on a 16-core
# platform). Let's restrict the number of created threads.
loader.env.OMP_NUM_THREADS = "8"
loader.env.MKL_NUM_THREADS = "8"
```

Do you have an idea how to get more detailed information to figure out what's going wrong?

**Comment by dzygann** [comment]
Hi @dimakuv ,
Unfortunately, no more output. 
I have tried the hello-world example and this works fine. There is an apt-get update command. 
I have extended the hello-world example to install also the other libs from the hashgraph dockerfile. This works fine. 
It seems that the tzdata makes the issue. I removed the `ARG DEBIAN_FRONTEND=noninteractive` and this came up:

```
Setting up tzdata (2021e-0ubuntu0.20.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
  2. America     5. Arctic     8. Europe    11. SystemV
  3. Antarctica  6. Asia       9. Indian    12. US
Geographic area:
```

Until now I couldn't find a solution. I tried all the solution proposals from [Serverfault - How to install tzdata on a ubuntu docker image](https://serverfault.com/questions/949991/how-to-install-tzdata-on-a-ubuntu-docker-image), but all of them doesn't work, when I try to run the `gsc build`.

**Comment by dimakuv** [comment]
Where does this `tzdata` come from? Unfortunately, I don't know all those Ubuntu packages and how their installation works. @woju @aneessahib @veenasai2 Any ideas what this could be?

**Comment by veenasai2** [comment]
@dzygann did you try this solution : https://rtfm.co.ua/en/docker-configure-tzdata-and-timezone-during-build/  ?

**Comment by dzygann** [comment]
Hi @veenasai2 
Yes, I also tried this one and it also works for `docker build`, but when I run the `gsc build` it stops without any further output. 
Is it possible to add somewhere a console output? It's quite hard to analyse this one without further information.

**Comment by dimakuv** [comment]
But `gsc build` already prints all console output. So there is no additional "hidden" output... That's why I'm so surprised that there are no error logs after `Step 8/22 : RUN apt-get update ...`.

This is where GSC reports the failure: https://github.com/gramineproject/gsc/blob/3c4f89a2b6fae06d4c5e5d030045dc115e58c16f/gsc.py#L234

As you can see, this happens immediately after the function `build_docker_image()`. The function looks like this: https://github.com/gramineproject/gsc/blob/master/gsc.py#L40-L49

You can see that the function simply invokes the Docker engine and redirects all Docker-build output to your console. Nothing is hidden by GSC.

**Comment by aneessahib** [comment]
@dzygann - does a basic ubuntu20.04 image running bash work in gsc for you? this always works for us. So may be something in you dockerfile is exposing an issue in gsc (or not). I suspect ```FROM scratch```

**Comment by veenasai2** [comment]
> @dzygann - does a basic ubuntu20.04 image running bash work in gsc for you? this always works for us. So may be something in you dockerfile is exposing an issue in gsc (or not). I suspect `FROM scratch`

Also, can you please try putting any RUN command (e.g. `RUN ls /`) after `FROM scratch AS export-stage` in your base image Dockerfile and build the base image again ? 

Please confirm here, if the build succeeds, this will help us debug faster. Thanks.

**Comment by dzygann** [comment]
Hi @veenasai2 

I have created the following dockerfile:

```
developer@OptiPlex-3070:~/workspaces/enclaive/gsc$ cat test/scratch.dockerfile 
From scratch AS export-stage

COPY hello /

CMD ["hello"]
```

The output from the console is the same. Is the `export-stage` triggering the issue?

**Comment by dimakuv** [comment]
I read a bit about `scratch` Docker images: https://docs.docker.com/develop/develop-images/baseimages/.

Yes, the problem is in this statement `FROM scratch`. Basically, this statement says "Remove absolutely everything from the Docker image, there will be no files, no directories, no commands, nothing at all". Which means that there will be no Ubuntu OS (its files, its directories, its commands) in the resulting base Docker image.

But GSC assumes that there is a proper Ubuntu in the base Docker image. But with `scratch` image, the very first Ubuntu-specific command (`RUN apt-get update`) fails because there is *no apt-get command* in the base image!

So yes, `FROM scratch` Docker images are not supported by GSC.

**Comment by dzygann** [comment]
Hi @dimakuv 
thanks for the clarification! I tried the following scenario. 

Create the dockerfile:
```
From ubuntu:20.04 

COPY hello /

CMD ["hello"]
```

The GSC run into the same issue: 
```
untime/glibc/'
Running custom install script '/bin/sh -c ln -sf ../../../libsecret_prov_verify_epid.so "$MESON_INSTALL_DESTDIR_PREFIX"/lib/x86_64-linux-gnu/gramine/runtime/glibc/'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-sgx-ias-verify-report'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-manifest'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-sgx-get-token'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-sgx-sign'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-direct'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-sgx'
Running custom install script '/bin/sh -c ln -sf legacy-graphene-to-gramine "$MESON_INSTALL_DESTDIR_PREFIX"/bin/graphene-argv-serializer'
 ---> af655d60aa63
Step 7/22 : FROM scratch

 ---> 
Step 8/22 : RUN apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y         binutils         libprotobuf-c-dev         locales         locales-all         openssl         python3         python3-pip         python3-protobuf     && python3 -B -m pip install click jinja2 protobuf 'toml>=0.10'

 ---> Running in 24cb6e8421cb
Failed to build unsigned graminized docker image `gsc-scratch-unsigned`.
```

I did a file search and found the `Step 7/22 : FROM scratch` in the build/gsc-scratch/Dockerfile.build. I took a look into the template [Dockerfile.ubuntu.build.template](https://github.com/gramineproject/gsc/blob/3c4f89a2b6fae06d4c5e5d030045dc115e58c16f/templates/Dockerfile.ubuntu.build.template#L9) and it seems it uses the dockerfile name to set the `app-image`. 
I renamed the dockerfile to `ubuntu18.04-scratch.manifest` and now the minimal example is working with the `gsc build` command.

**Comment by dimakuv** [comment]
@dzygann Glad it works now!

This is an interesting observation. You called your Dockerfile `scratch.dockerfile` which conflicts with the Docker's keyword. Of course, a simple solution is to never use Docker keywords in your filenames.

But GSC should disallow such keywords in filenames, I guess. This should be simple to implement. @veenasai2 @aneessahib What do you think, should we check the `app-image` GSC-build argument and loudly fail -- or at least give a warning -- that the base Dockerimage filename is a "keyword in Docker, and it may lead to unexpected results. Consider renaming your original Docker image".

**Comment by aneessahib** [comment]
@dimakuv - I'm not sure if I'm missing something. In above case i figure, the base image name is identical to a standard docker image (scratch). I cant think of an easy way to implement a check of the base image name against hundreds of docker images . I think it would be better in general if one avoids creating base images with names that conflicts with standard docker images. 

Just to clarify (since i noticed dockerfiles/manifest being mentioned) - The dockerfile and manifest files could be of any name. We pass the actual base image name to GSC build.  So - unless the base image itself was named ```scratch```  - this shouldnt happen.

**Comment by dimakuv** [comment]
> Just to clarify (since i noticed dockerfiles/manifest being mentioned) - The dockerfile and manifest files could be of any name. We pass the actual base image name to GSC build. So - unless the base image itself was named scratch - this shouldnt happen.

Ah, sorry, then I was wrong. I thought that GSC takes the dockerfile/manifest file name as the "base image name". So ignore my comment then.

@dzygann Does this resolve all your issues? Should we close this issue now?

**Comment by dzygann** [comment]
Hi,
yes, we can close this issue. 
Thanks for your help!
