### ISSUE TITLE
gethostname inside gsc container appears to revert back to docker host's hostname instead of container ID

### ISSUE THREAD

**Issue by mleberec** [gramineproject/gsc#39]
## Description of the problem

I noticed that the gethostname function inside container does not report the same result when running as plain docker container (where it produces the container id in docker) compared to running a gramenized gsc-image (where it appears to provide the underlying node OS's hostname)

## Steps to reproduce

Simple python web server providing back own hostname:

```
#!/usr/bin/env python3

import socket

import sys
from http.server import BaseHTTPRequestHandler, HTTPServer

class DummyRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        my_id = socket.gethostname()
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        print("container id:")
        print(my_id)
        self.wfile.write(my_id.encode())


def main(argv):
    if len(argv) != 2:
        print(f'Usage: {argv[0]} <PORT>', file=sys.stderr)
        return 1

    port = int(argv[1])
    srv = HTTPServer(('0.0.0.0', port), DummyRequestHandler)
    srv.serve_forever()
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))

```

## Expected results
Running

```
python3 servehostname.py 12345 & 
curl localhost:12345

```
gives back machine's hostname  --> expected.

Doing a _docker build image_ and   _docker run image_

Running same `curl localhost:12345` will yield _containerID_ as hostname. --> also expected.

You would expect the same _containerID_ when run as gsc image. 

## Actual results

However, when running the gsc-built and signed image, the result will nwo again be the machine's hostname, resulting in multiple gsc containers on the same host having an identical hostname.

**Comment by dimakuv** [comment]
@mkow @aneessahib @veenasai2 Anyone willing to look into this issue?

My suspicion is that the Docker engine intercepts `gethostname()` system call (probably via the seccomp policy, which we override in Gramine/GSC), and replaces the reply from the host Linux kernel with Docker's own reply.

**Comment by aneessahib** [comment]
yes i can check after my current stuffs are done. pls assign

**Comment by veenasai2** [comment]
@dimakuv We are seeing the same issue in gramine as well.  

```
python3 servehostname.py 12345 & 
curl localhost:12345
```
gives back "machine's hostname" whereas inside gramine / gramine-sgx / gsc-container we are getting "localhost" as hostname. 

Thanks.

**Comment by dimakuv** [comment]
@veenasai2 Any idea why this can happen? Hopefully a bit of googling can shed light on this problem.

**Comment by mleberec** [comment]
Any progress on this here or at Gramine? I tried the scenario today and am still getting the faulty response.

**Comment by dimakuv** [comment]
Hm, I don't think anyone had time to check this... @aneessahib ?

**Comment by dimakuv** [comment]
@mleberec Can you add `sys.enable_extra_runtime_domain_names_conf = true` to your manifest file for GSC?

**Comment by mleberec** [comment]
Thanks, @dimakuv, that solved it.

**Comment by dimakuv** [comment]
@mleberec Awesome! I'm not sure how to reflect this in GSC... Do you think we should put it into documentation, or as an additional flag to `gsc build ...`, or something else?

I don't want to enable it by default as it doesn't make sense for non-network apps...

**Comment by mleberec** [comment]
I would make a small subsection in the "Limitations" section of gsc documentation. That keeps the effort low but points it out in the gsc context.

**Comment by dimakuv** [comment]
@mleberec Just for history: done, here https://github.com/gramineproject/gsc/pull/122

**Comment by aneessahib** [comment]
Sorry @dimakuv  - Couldn't respond earlier. Glad to know the `resolv.conf` sanitization helped here.
