### ISSUE TITLE
Failure in gsc sign-image due to protobuf major upgrade

### ISSUE THREAD

**Issue by rranjan3** [gramineproject/gsc#65]
This appears to be a failure due to update in major release version of protobuf from 3.20.1 to 4.21.0 - https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Below are the logs when I attempt to run `gsc sign-image IMAGE_NAME SIGNING_KEY_FILE`

```
...
Step 2/6 : COPY gsc-signer-key.pem /gsc-signer-key.pem

 ---> aa1594fff42b
Step 3/6 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && gramine-sgx-sign       --key /gsc-signer-key.pem       --manifest /entrypoint.manifest       --output /entrypoint.manifest.sgx

 ---> Running in a3c8fd7333a5
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 11, in <module>
    from graminelibos import (
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/__init__.py", line 24, in <module>
    from .sgx_get_token import get_token
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/sgx_get_token.py", line 9, in <module>
    from . import _aesm_pb2 as aesm_pb2
  File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/_aesm_pb2.py", line 38, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Removing intermediate container a3c8fd7333a5
```

**Comment by mkow** [comment]
Seems https://github.com/gramineproject/gramine/issues/155 got more urgent...

**Comment by dimakuv** [comment]
@rranjan3 What is your image and how does your GSC's `config.yaml` look like? I'm particularly interested in the OS distro version -- is it Ubuntu 22.04? Because I tried on my Ubuntu 18.04 and Ubuntu 20.04, and building the example Python image with GSC worked fine.

@rranjan3 Also, have you tried to modify https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.common.sign.template for a `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION` workaround? You could add smth like `ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` before line 6. If this works, we can use this workaround for now (you can submit a PR or just tell us if this workaround works, and we'll submit the PR ourselves).

@mkow Yes.

**Comment by rranjan3** [comment]
@dimakuv , I had built gramine base over 20.04 & then was using this as base image in config.yaml.

I was not building the sample python application though. My workload is a multi-stage docker image of OpenVino. For now, the fix that worked for me is adding the following to the last stage -
RUN python3 -m pip install --no-cache-dir --upgrade pip; \
    python3 -m pip install protobuf==3.20.*

**Comment by dimakuv** [comment]
@rranjan3 Thanks for the explanation. However, I don't like to hard-code the protobuf version and get it from pip (instead of Ubuntu/CentOS own packages, see e.g. https://github.com/gramineproject/gsc/blob/5c39dddaadd081f7716a80de5221a7f88ed67e12/templates/ubuntu/Dockerfile.build.template#L14?plain=1).

@veenasai2 @aneessahib We should reproduce this error and provide a workaround of `ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` for now. Until we fix it properly in the core Gramine repo ( https://github.com/gramineproject/gramine/issues/155), which may not happen soon...

**Comment by rranjan3** [comment]
WIth the suggested fix in Docker.common.sign.template, the signing and build runs just fine. But I see the same error log when trying to run the graminized image.
```
Attaching to openvino-ssd_ov-ssd-engine_1
ov-ssd-engine_1  | Traceback (most recent call last):
ov-ssd-engine_1  |   File "/gramine/meson_build_output/bin/gramine-sgx-get-token", line 8, in <module>
ov-ssd-engine_1  |     from graminelibos import Sigstruct, get_token
ov-ssd-engine_1  |   File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/__init__.py", line 24, in <module>
ov-ssd-engine_1  |     from .sgx_get_token import get_token
ov-ssd-engine_1  |   File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/sgx_get_token.py", line 9, in <module>
ov-ssd-engine_1  |     from . import _aesm_pb2 as aesm_pb2
ov-ssd-engine_1  |   File "/gramine/meson_build_output/lib/python3.8/site-packages/graminelibos/_aesm_pb2.py", line 38, in <module>
ov-ssd-engine_1  |     _descriptor.FieldDescriptor(
ov-ssd-engine_1  |   File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 560, in __new__
ov-ssd-engine_1  |     _message.Message._CheckCalledFromGeneratedFile()
ov-ssd-engine_1  | TypeError: Descriptors cannot not be created directly.
ov-ssd-engine_1  | If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
ov-ssd-engine_1  | If you cannot immediately regenerate your protos, some other possible workarounds are:
ov-ssd-engine_1  |  1. Downgrade the protobuf package to 3.20.x or lower.
ov-ssd-engine_1  |  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
ov-ssd-engine_1  |
ov-ssd-engine_1  | More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
openvino-ssd_ov-ssd-engine_1 exited with code 1
```

**Comment by dimakuv** [comment]
@rranjan3 Fair enough, I forgot about the other place which needs fixing.

Please add the envvar in this line: https://github.com/gramineproject/gsc/blob/5c39dddaadd081f7716a80de5221a7f88ed67e12/templates/apploader.common.template#L14

So it will become like this:
```
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python gramine-sgx-get-token --quiet \
```

**Comment by dimakuv** [comment]
@rranjan3 I created https://github.com/gramineproject/gsc/pull/71. If you can, please try it out and report your results.

**Comment by rranjan3** [comment]
Thanks @dimakuv . Able to verify the gsc openvino example in the repo. Also, need to try the OpenVino SSD example with changes similar to the Openvino sample here.
