### ISSUE TITLE
Unable to install `python3-pyelftools` on CentOS

### ISSUE THREAD

**Issue by aniket-intelx** [gramineproject/gsc#75]
## Description of the problem
We are unable to install `python3-pyelftools` on CentOS and getting below error message.
```
No match for argument: python3-pyelftools
Error: Unable to find a match: python3-pyelftools
```
When tried installing on bare-metal, we found that this package is provided by `epel.repo` by the following command
```
sudo yum list installed | grep pyelf
python3-pyelftools.noarch                          0.27-5.el8                                                 @epel
```
## Actual results

```
Step 3/6 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib64 -type d -path '*/site-packages')" && gramine-sgx-sign       --key /gramine/app_files/gsc-signer-key.pem       --manifest /gramine/app_files/entrypoint.manifest       --output /gramine/app_files/entrypoint.manifest.sgx

 ---> Running in 819acb7b78ae
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 11, in <module>
    from graminelibos import (
  File "/gramine/meson_build_output/lib64/python3.6/site-packages/graminelibos/__init__.py", line 25, in <module>
    from .sgx_sign import get_tbssigstruct, sign_with_local_key, SGX_LIBPAL, SGX_RSA_KEY_PATH
  File "/gramine/meson_build_output/lib64/python3.6/site-packages/graminelibos/sgx_sign.py", line 19, in <module>
    import elftools.elf.elffile
ModuleNotFoundError: No module named 'elftools'
```

**Comment by dimakuv** [comment]
Is there a way to use EPEL? What's the reason not to add EPEL repo to our CentOS Dockerfile?

**Comment by jinengandhi-intel** [comment]
> Is there a way to use EPEL? What's the reason not to add EPEL repo to our CentOS Dockerfile?

Dmitrii, we raised an issue to get that feedback exactly, in the current setup we see this failure and the fix is to add the EPEL repo.

**Comment by dimakuv** [comment]
I see. Could you submit a PR for this?

Also, I will start verifying my PRs with CentOS as well (if they modify something in CentOS). Sorry for this blooper...

**Comment by aniket-intelx** [comment]
When we tried installing `python3-pyelftools` after the installation of `epel-release`, it worked.
`RUN dnf install -y python3-pyelftools`

Please find our dockerfile (Line no. 24) attached.

[CentOS_Dockerfile_build_template.txt](https://github.com/gramineproject/gsc/files/9091708/CentOS_Dockerfile_build_template.txt)

**Comment by dimakuv** [comment]
@aniket-intelx Do you want to submit a PR to fix this issue?

**Comment by dimakuv** [comment]
@aniket-intelx Could you remind what happened with this issue?

**Comment by jinengandhi-intel** [comment]
@dimakuv  this issue should be closed, a fix for this was pushed here: https://github.com/gramineproject/gsc/commit/e7073b7d4444c6943afcc08cdf60da0dd39f747c
