### ISSUE TITLE
error while build and install Gramine

### ISSUE THREAD

**Issue by gus6202** [gramineproject/gsc#84]
## Description of the problem
After step ``setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled \`` when I build gramine using ninja command the following error comes up:

``
~/Desktop/gramine$ ninja -C build/
ninja: Entering directory `build/'
[0/19] Generating subprojects/glibc-2.34-1/glibc with a custom command
glibc: see /home/augusto/Desktop/gramine/build/subprojects/glibc-2.34-1/glibc-build.log for full build log
glibc: preparing sources...
glibc: running configure...
[16/18] Linking target Pal/src/host/Li...s-report/gramine-sgx-ias-verify-report
FAILED: subprojects/glibc-2.34-1/crt1.o subprojects/glibc-2.34-1/crti.o subprojects/glibc-2.34-1/crtn.o subprojects/glibc-2.34-1/libdl.so subprojects/glibc-2.34-1/libdl.so.2 subprojects/glibc-2.34-1/libc.so subprojects/glibc-2.34-1/libc.so.6 subprojects/glibc-2.34-1/libutil.so subprojects/glibc-2.34-1/libutil.so.1 subprojects/glibc-2.34-1/libm.so subprojects/glibc-2.34-1/libm.so.6 subprojects/glibc-2.34-1/libnsl.so subprojects/glibc-2.34-1/libnsl.so.1 subprojects/glibc-2.34-1/libpthread.so subprojects/glibc-2.34-1/libpthread.so.0 subprojects/glibc-2.34-1/libthread_db.so subprojects/glibc-2.34-1/libthread_db.so.1 subprojects/glibc-2.34-1/libnss_compat.so subprojects/glibc-2.34-1/libnss_compat.so.2 subprojects/glibc-2.34-1/libnss_db.so subprojects/glibc-2.34-1/libnss_db.so.2 subprojects/glibc-2.34-1/libnss_files.so subprojects/glibc-2.34-1/libnss_files.so.2 subprojects/glibc-2.34-1/libanl.so subprojects/glibc-2.34-1/libanl.so.1 subprojects/glibc-2.34-1/libnss_dns.so subprojects/glibc-2.34-1/libnss_dns.so.2 subprojects/glibc-2.34-1/libresolv.so subprojects/glibc-2.34-1/libresolv.so.2 subprojects/glibc-2.34-1/librt.so subprojects/glibc-2.34-1/librt.so.1 subprojects/glibc-2.34-1/ld-linux-x86-64.so.2 subprojects/glibc-2.34-1/ld.so subprojects/glibc-2.34-1/libmvec.so subprojects/glibc-2.34-1/libmvec.so.1 
/bin/sh /home/augusto/Desktop/gramine/subprojects/glibc-2.34-1/compile.sh x86_64 ../subprojects/glibc-2.34-1 ../subprojects/glibc-2.34-1/glibc-2.34 /home/augusto/Desktop/gramine/build/subprojects/glibc-2.34-1 subprojects/glibc-2.34-1/crt1.o.p /usr/local lib/x86_64-linux-gnu '' csu/crt1.o csu/crti.o csu/crtn.o dlfcn/libdl.so dlfcn/libdl.so.2 libc.so libc.so.6 login/libutil.so login/libutil.so.1 math/libm.so math/libm.so.6 nis/libnsl.so nis/libnsl.so.1 nptl/libpthread.so nptl/libpthread.so.0 nptl_db/libthread_db.so nptl_db/libthread_db.so.1 nss/libnss_compat.so nss/libnss_compat.so.2 nss/libnss_db.so nss/libnss_db.so.2 nss/libnss_files.so nss/libnss_files.so.2 resolv/libanl.so resolv/libanl.so.1 resolv/libnss_dns.so resolv/libnss_dns.so.2 resolv/libresolv.so resolv/libresolv.so.2 rt/librt.so rt/librt.so.1 elf/ld-linux-x86-64.so.2 elf/ld.so mathvec/libmvec.so mathvec/libmvec.so.1
ninja: build stopped: subcommand failed.
``

**Comment by dimakuv** [comment]
I don't think this is the full log. It looks truncated.

**Comment by gus6202** [comment]
Hey, I rebuild meson step and now it's working, thanks.
