### ISSUE TITLE
A question about gsc-build.

### ISSUE THREAD

**Issue by Yang-yyf** [gramineproject/gsc#85]
### Questions

I encountered some errors when building a simple HelloWorld image. It appears that some downloads failed to complete in the build section due to network problems. Should I try to go into the image and change the "source. txt" in it or modify the command in a file called "dockerfile.build" to add a copy file operation?

**Comment by mkow** [comment]
Quoting the issue template you deleted:

> IMPORTANT: please do not post general questions here;
> if you have questions, please use our mailing list: users@gramineproject.io

We use issues only to track bugs, not for user support. Also, please include more detail and logs, the description you posted is super vague.
