### ISSUE TITLE
Add Debain 11 to the list of supported distros

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gsc#86]
## Description of the problem
The distro on the Redis docker image is debain 11 and providing `Debain11` to config.yaml.template doesn't result in any issues. So we should add Debain 11 as one of the supported distros.

**Comment by aneessahib** [comment]
So all that we need to do here is to just `cp /templates/ubuntu /templates/debian`  . And then make the `Debian11` change in config.yaml, before doing a `\gsc build .... `. 
Correct @jinengandhi-intel  ?

**Comment by jinengandhi-intel** [comment]
yes that's it. but for each distro will we keep on copying and creating folders, is there a better way?

**Comment by dimakuv** [comment]
Thanks for checking `Debian11`. Nice that it "just works".

Maybe we should use symlinks? `ln -s ubuntu debian` -- it will create a symlink directory `debian/` that will actually point to `ubuntu/`. This should be enough.

@mkow @woju @boryspoplawski Is it fine to have symlinks in the Git repo? Or are we against this?
