### ISSUE TITLE
Building Gramine base image fails due to failed intel-sgx-deb.key copy

### ISSUE THREAD

**Issue by manju956** [gramineproject/gsc#93]
While trying to build base gramine image, I am encountering build failures due to lack of key availability.

Command: ./gsc build-gramine gramine-base
Output: Step 3/9 : COPY intel-sgx-deb.key /

Failed to build a base-Gramine image `gsc-gramine-base`.

Config.yaml file contents are as described below.

Distro: "ubuntu:20.04"
Registry: ""

Gramine:
    Repository: "https://github.com/gramineproject/gramine.git"
    Branch:     "v1.2"

After having look into gsc.py, the below line was missing in "def gsc_build_gramine(args)" function.
shutil.copyfile('keys/intel-sgx-deb.key', tmp_build_path / 'intel-sgx-deb.key')

Raised PR https://github.com/gramineproject/gsc/pull/92 to address the issue.

**Comment by dimakuv** [comment]
This was fixed in #96, forgot to close this issue when merging that PR
